[book]
authors = [
    "LightArrowsEXE"
]
language = "en"
multilingual = false
src = "src"
title="Wobbly Guide"

[build]
create-missing = false

[output.html]
default-theme = "navy"
curly-quotes = true
mathjax-support = true
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-highlight.css"]
no-section-label = true
git-repository-url = "https://github.com/Irrational-Encoding-Wizardry/wobbly-guide"
